apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cloudserve
  name: config
data:
  API_PORT: "5000"
  GATEWAY_PORT: "5001"
  SANDBOX_PORT: "5002"
  SANDBOX_URL: "http://sandbox-service:5002"
  NODE_ENV: "development"
  MONGO_URI: "mongodb://mongo:27017/serverless"
  FAAS_URL: "http://cloudserve.local.com"
  MINIO_ENDPOINT: "minio"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET_NAME: "functions"
  STORAGE_PATH: "/app/storage/functions"
