apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  API_PORT: "5000"
  GATEWAY_PORT: "5001"
  SANDBOX_PORT: "5002"
  NODE_ENV: "development"
  FAAS_URL: "http://api-service:5000"
  MINIO_ENDPOINT: "minio"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET_NAME: "functions"
  STORAGE_PATH: "/app/storage/functions"
